BEGIN;
CREATE TABLE IF NOT EXISTS account ( 
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
    fullname VARCHAR(100) NOT NULL,
    email VARCHAR(62) NOT NULL UNIQUE,
    passhash VARCHAR(60) NOT NULL,
    account_type INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS doctor ( 
    id INTEGER PRIMARY KEY NOT NULL UNIQUE 
);
COMMIT;